### PR TITLE
Migrated from HCL to HCL2

### PR DESCRIPTION
**Pull request by Ghost---Shadow**
Fix for https://github.com/LinusU/gopher-hcl/issues/4

Hasicorp uses a different repository for HCL2

### CODE REVIEW

**Comment by mytototo** [comment]
Any plan to see a new release supporting the latest version of HCL?

**Comment by Ghost---Shadow** [comment]
@mytototo 

Meanwhile you can `npm i https://github.com/Ghost---Shadow/gopher-hcl#master`

**Comment by richardgavel** [comment]
HCL2 is no longer in the hcl2 repository. See https://github.com/hashicorp/hcl2#experimental-hcl2

**Comment by Ghost---Shadow** [comment]
Cool

**Comment by LinusU** [comment]
Hey! Sorry for not looking into this earlier!

It seems like they have moved the v2 code to the main repository, but at the moment it requires Go Modules to use, which GopherJS doesn't support yet. I'll open another issue to track this.

Thanks

**Pull request closed without merging**
